### ISSUE TITLE
Running in docker gives EOF error on PUT request

### ISSUE THREAD

**Issue by ckortekaas** [Tapico/tapico-turborepo-remote-cache#16]
Firstly - thanks for this extremely useful addon for Turborepo! Very impressive!

I have no problems using the downloadable executable, but using the docker container from the registry or built locally gives this error when turbo tries to connect eg:

```
2021-12-28T16:58:10.774+1000 [DEBUG] run: performing request: method=PUT url=http://127.0.0.1:8080/v8/artifacts/dad54db4bd311da2?teamId=team_test
2021-12-28T16:58:10.807+1000 [ERROR] run: request failed: error="Put "http://127.0.0.1:8080/v8/artifacts/dad54db4bd311da2?teamId=team_test": EOF" method=PUT url=http://127.0.0.1:8080/v8/artifacts/dad54db4bd311da2?teamId=team_test
```

That's running with an apiUrl and teamId set in `./turbo/config.json` via turbo eg:

```
TURBO_TOKEN=testtoken yarn turbo run build  -vvv --force
```

Other things I've tried result in a connection refused error instead, so EOF seems to imply it's connecting but failing to PUT. I'm using S3 with valid credentials that work with the non-docker version. I've even modified the container to execute inside it manually various commands to make sure it's not that the command arguments are not being mistranslated somehow. 

This is what I've been using in docker-compose:

```
  tapico-turborepo-cache:
    container_name: dev_tapico-turborepo-cache
    image: ghcr.io/tapico/tapico-turborepo-remote-cache:sha-152ba94
    networks:
      - internal
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    entrypoint: /bin/sh
    command: -c "/go/bin/tapico-turborepo-remote-cache --turbo-token=testtoken --kind=s3 --s3.region=us-east-1 --bucket=test-turborepo-cache -v"
```

The is only the Turbo 1.0.23 and 0.0.8.

I'm a little rusty on my Docker and haven't used Go before but I couldn't see anything obviously wrong in either.

Is it possible to show a working example of a docker-compose wrapped around tapico-turborepo-remote-cache that allows the host (eg MacOS) to run turbo against it successfully? Thanks!
